# **Import Libraries**

In [1]:
import pandas as pd
import pickle
import numpy as np
from sklearn.metrics import classification_report
from IPython.display import display, HTML

C:\Users\asus\AppData\Local\Temp\ipykernel_12480\3084629039.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# **Data Loading**

In [14]:
'''Import data dari csv'''

df = pd.read_csv('inference_data.csv', delimiter=',')
df.head()

,previous,pdays,duration,poutcome,month,contact,housing,job,loan,education,marital,y_encoded
0,6,178,13,success,may,cellular,yes,blue-collar,no,secondary,married,0
1,0,-1,461,unknown,may,unknown,yes,blue-collar,no,secondary,single,0
2,0,-1,210,unknown,apr,cellular,yes,technician,no,secondary,married,0
3,0,-1,356,unknown,nov,cellular,no,unemployed,no,secondary,single,0
4,0,-1,318,unknown,nov,cellular,yes,management,no,tertiary,married,0

In [15]:
'''Menghitung proporsi kelas minoritas dan mayoritas untuk menentukan penggunaan model'''

# Menghitung jumlah masing-masing nilai pada kolom 'y_encoded'
value_counts = df['y_encoded'].value_counts()
print("Jumlah masing-masing nilai pada kolom 'y_encoded':")
print(value_counts)

# Menghitung persentase kelas minoritas (nilai 1)
total_count = len(df)
minority_class_count = value_counts.get(1, 0)
minority_class_percentage = (minority_class_count / total_count) * 100

print(f"Persentase kelas minoritas (1) pada kolom 'y_encoded': {minority_class_percentage:.2f}%")

Jumlah masing-masing nilai pada kolom 'y_encoded':
y_encoded
0    1996
1     265
Name: count, dtype: int64
Persentase kelas minoritas (1) pada kolom 'y_encoded': 11.72%

Berdasarkan perhitungan diketahui bahwa proporsi kelas minoritas (1) pada data hanya 11,72% dari total data yang berarti data ini terindikasi imbalance, sehingga model yang akan digunakan untuk data ini adalah model yang sudah melalui oversampling dan hyperparameter tuning.

In [16]:
'''Memuat model dari file'''

with open('xgb_pipeline_tuning_smote.pkl', 'rb') as file_model:
    grid_search_smote_tuned_loaded = pickle.load(file_model)

In [17]:
'''Prediksi'''
predictions = grid_search_smote_tuned_loaded.predict(df)

In [18]:
'''Menambahkan hasil prediksi ke DataFrame'''
df['Predictions'] = predictions

In [19]:
'''Membuat tampilan scrollable untuk DataFrame agar lebih mudah dibaca'''

html = df.to_html()
scrollable_html = f"""
<div style="height:500px; overflow:auto; border:1px solid black; padding:10px">
{html}
</div>
"""

# Menampilkan DataFrame yang telah digabungkan dengan hasil prediksi
display(HTML(scrollable_html))

In [22]:
'''Menampilkan Classification Report'''

y_true = df['y_encoded']

# Menampilkan Classification Report
print("Classification Report:")
print(classification_report(y_true, predictions))

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.69      0.81      1996
           1       0.28      0.89      0.42       265

    accuracy                           0.71      2261
   macro avg       0.63      0.79      0.61      2261
weighted avg       0.90      0.71      0.76      2261